version: '2'
services:
  citydeals-app:
    image: citydeals
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://citydeals-postgresql:5432/CityDeals
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://citydeals-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://citydeals-elasticsearch:9200
    ports:
      - 8080:8080
  citydeals-postgresql:
    extends:
      file: postgresql.yml
      service: citydeals-postgresql
  citydeals-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: citydeals-elasticsearch
